//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSPTitleGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\toti9\\Downloads\\")]
        public string OutputDirectory {
            get {
                return ((string)(this["OutputDirectory"]));
            }
            set {
                this["OutputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("145, 885")]
        public global::System.Drawing.Point BlockNameLocation {
            get {
                return ((global::System.Drawing.Point)(this["BlockNameLocation"]));
            }
            set {
                this["BlockNameLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1920, 1080")]
        public global::System.Drawing.Size OutputImageSize {
            get {
                return ((global::System.Drawing.Size)(this["OutputImageSize"]));
            }
            set {
                this["OutputImageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("193, 931")]
        public global::System.Drawing.Point VariantsLocation {
            get {
                return ((global::System.Drawing.Point)(this["VariantsLocation"]));
            }
            set {
                this["VariantsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("273, 977")]
        public global::System.Drawing.Point CustomMoldeLocation {
            get {
                return ((global::System.Drawing.Point)(this["CustomMoldeLocation"]));
            }
            set {
                this["CustomMoldeLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("252, 1023")]
        public global::System.Drawing.Point CTMSupportLocation {
            get {
                return ((global::System.Drawing.Point)(this["CTMSupportLocation"]));
            }
            set {
                this["CTMSupportLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 106, 64")]
        public global::System.Drawing.Color OverworldColorCode {
            get {
                return ((global::System.Drawing.Color)(this["OverworldColorCode"]));
            }
            set {
                this["OverworldColorCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("118, 61, 59")]
        public global::System.Drawing.Color NetherColorCode {
            get {
                return ((global::System.Drawing.Color)(this["NetherColorCode"]));
            }
            set {
                this["NetherColorCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("235, 243, 181")]
        public global::System.Drawing.Color EndColorCode {
            get {
                return ((global::System.Drawing.Color)(this["EndColorCode"]));
            }
            set {
                this["EndColorCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 856")]
        public global::System.Drawing.Point BlockBackgroundLocation {
            get {
                return ((global::System.Drawing.Point)(this["BlockBackgroundLocation"]));
            }
            set {
                this["BlockBackgroundLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("113, 1023")]
        public global::System.Drawing.Point ItemNameLocation {
            get {
                return ((global::System.Drawing.Point)(this["ItemNameLocation"]));
            }
            set {
                this["ItemNameLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("153, 1023")]
        public global::System.Drawing.Point EntityNameLocation {
            get {
                return ((global::System.Drawing.Point)(this["EntityNameLocation"]));
            }
            set {
                this["EntityNameLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 994")]
        public global::System.Drawing.Point SingleBackgroundLocation {
            get {
                return ((global::System.Drawing.Point)(this["SingleBackgroundLocation"]));
            }
            set {
                this["SingleBackgroundLocation"] = value;
            }
        }
    }
}
